// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOceZ4s5K6UtF6cND-yVRJA3B24wJNWS0',
    appId: '1:3663967250:web:19e8139b306cc18c1714cb',
    messagingSenderId: '3663967250',
    projectId: 'find-your-teammate-fe8ec',
    authDomain: 'find-your-teammate-fe8ec.firebaseapp.com',
    storageBucket: 'find-your-teammate-fe8ec.firebasestorage.app',
    measurementId: 'G-3QHMQHJEV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmuCdZM3GLM--8SM-dG6XLRKqJfWpb9I4',
    appId: '1:3663967250:android:ff984d7d55e2b2771714cb',
    messagingSenderId: '3663967250',
    projectId: 'find-your-teammate-fe8ec',
    storageBucket: 'find-your-teammate-fe8ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4q-03WXS5iht5zHza6ab-3l4qziwJ-bk',
    appId: '1:3663967250:ios:af62156b76168dc21714cb',
    messagingSenderId: '3663967250',
    projectId: 'find-your-teammate-fe8ec',
    storageBucket: 'find-your-teammate-fe8ec.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4q-03WXS5iht5zHza6ab-3l4qziwJ-bk',
    appId: '1:3663967250:ios:af62156b76168dc21714cb',
    messagingSenderId: '3663967250',
    projectId: 'find-your-teammate-fe8ec',
    storageBucket: 'find-your-teammate-fe8ec.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOceZ4s5K6UtF6cND-yVRJA3B24wJNWS0',
    appId: '1:3663967250:web:32b9242f220211721714cb',
    messagingSenderId: '3663967250',
    projectId: 'find-your-teammate-fe8ec',
    authDomain: 'find-your-teammate-fe8ec.firebaseapp.com',
    storageBucket: 'find-your-teammate-fe8ec.firebasestorage.app',
    measurementId: 'G-KYSX8MECKP',
  );
}
